account/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('my_videos' , my_videos , name = 'my_videos'),
    path('create_video_info' , create_video_info , name = 'create_video_info'),
    path('edit_video_info' , edit_video_info , name = 'edit_video_info'),
]

test_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('' , test , name = 'test'),
    path('result/' , result , name = 'result'),
]

video/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
        path('' , index , name = 'index'),
        path('play_video' , play_video , name = 'play_video'),
        path('list_video' , list_video , name = 'list_video'),
        path('list_type' , list_type , name = 'list_type'),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

video_web/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('video.urls')),
    path('account/' , include('account.urls')),
    path('search' , search , name = 'search'),
    path('test/' , include('test_app.urls')),
]

account/models.py
from django.db import models

# Create your models here.

test_app/models.py
from django.db import models

# Create your models here.

def upload_to_img(instance , filename):
    return 'test/%s/%s.jpeg'%(instance.title , filename)

class TestModel(models.Model):
    title = models.CharField(max_length = 50 , verbose_name = '测试标题')
    content = models.TextField(verbose_name = '测试内容')
    image = models.ImageField(upload_to = upload_to_img , verbose_name = '图片')

video/models.py
from django.db import models

# Create your models here.
#图片上传保存路径
def up_to_img(instance , filename):
    return 'video/%s/%s/img/%s'%(instance.video_type.title , instance.video_title , filename)

#视频上传保存路径
def up_to_video(instance , filename):
    return 'video/%s/%s/video/%s'%(instance.title.video_type.title , instance.title.video_title , filename)

#视频分类
class Video_type(models.Model):
    title = models.CharField(max_length = 50 , verbose_name = '视频分类')
    def __str__(self):
        return self.title

#视频信息
class Video_info(models.Model):
    video_type = models.ForeignKey(Video_type , on_delete = models.DO_NOTHING , verbose_name = '视频分类')
    video_title = models.CharField(max_length = 50 , verbose_name = '视频名称')
    video_detail = models.TextField(verbose_name = '视频内容简述')
    video_img = models.ImageField(upload_to = up_to_img , verbose_name = '图片')
    def __str__(self):
        return self.video_title

#视频
class Video(models.Model):
    title = models.ForeignKey(Video_info , on_delete = models.DO_NOTHING , verbose_name = '视频')
    video = models.FileField(upload_to = up_to_video , verbose_name = '视频')
    name = models.CharField(max_length = 50 , default = '无' , verbose_name = '视频名称')
    def __str__(self):
        return self.title.video_title

account/forms.py
from video.models import *
from django import forms

class Video_infoForm(forms.ModelForm):
    class Meta:
        model = Video_info
        fields = ('video_type' , 'video_title' , 'video_detail')
        widgets = {
            "video_type":forms.Select(attrs={'class':'form-control'}),
            "video_title":forms.TextInput(attrs={'class':'form-control'}),
            "video_detail":forms.Textarea(attrs={'class':'form-control'}),
        }

test_app/forms.py
from django import forms
from .models import *

class TestModelForm(forms.ModelForm):
    class Meta:
        model = TestModel
        fields = ('title' , 'content')

account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from video.models import Video_info
from django.http import HttpResponse
from .forms import *

# Create your views here.

@login_required
def my_videos(request):
    video_infos = Video_info.objects.all()
    context = {}
    context['video_infos'] = video_infos
    return render(request , 'account/my_videos.html' , context)

@login_required
def create_video_info(request):
    if request.method == 'POST':
        form = Video_infoForm(request.POST)
        upload_image = request.FILES.get('image')
        if form.is_valid():
            new_video_info = form.save(commit=False)
            new_video_info.video_img = upload_image
            new_video_info.save()
            return HttpResponse('1')
        else:
            return HttpResponse('error')
    else:
        form = Video_infoForm()
        context = {}
        context['form'] = form
        return render(request , 'account/create_video_info.html' , context) 

@login_required
def edit_video_info(request):
    video_info_id = request.GET.get('video_info_id')
    video_info = Video_info.objects.get(id = video_info_id)
    if request.method == "POST":
        form = Video_infoForm(instance = video_info , data = request.POST)
        upload_image = request.FILES.get('image')
        if form.is_valid():
            if upload_image:
                new_video_info = form.save(commit = False)
                new_video_info.video_img = upload_image
                new_video_info.save()
            else:
                form.save()
            return HttpResponse('1')
        else:
            return HttpResponse('error')
    else:
        form = Video_infoForm(instance = video_info)
        context = {}
        context['form'] = form
        context['video_info'] = video_info
        return render(request , 'account/edit_video_info.html' , context)

test_app/views.py
from django.shortcuts import render , redirect
from .models import *
from .forms import *
from django.urls import reverse
from django.http import HttpResponse

# Create your views here.

def test(request):
    if request.method == "POST":
        form = TestModelForm(request.POST)
        if form.is_valid():
            print(2)
            new_test = form.save(commit=False)
            new_test.image = request.FILES.get('image')
            new_test.save()
            return HttpResponse('1')
        else:
            return HttpResponse('2')
    else:
        form = TestModelForm()
        return render(request , 'test/test.html' , {'form':form})

def result(request):
    img = TestModel.objects.last()
    context = {}
    context['img'] = img
    return render(request , 'test/test2.html' , context)

video/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
#主页
def index(request):
    list_video = Video_info.objects.filter(video_type__title = '电视剧')
    context = {}
    context['list_video'] = list_video
    return render(request , 'video/index.html' , context)

#分类列表
def list_type(request):
    video_type = request.GET.get('video_type')
    list_video = Video_info.objects.filter(video_type__title = video_type)
    context = {}
    context['list_video'] = list_video
    return render(request , 'video/list_type.html' , context)

#播放
def play_video(request):
    video_id = request.GET.get('video_id')
    video = Video.objects.get(id = video_id)
    context = {}
    context['video'] = video
    return render(request , 'video/play_video.html' , context)

#视频列表
def list_video(request):
    video_info_id = request.GET.get('video_info_id')
    video = Video_info.objects.get(id = video_info_id)
    context = {}
    context['video'] = video
    return render(request , 'video/list_video.html' , context)

video_web/views.py
from video.models import *
from django.views.decorators.http import require_POST
from django.shortcuts import render
from django.db.models import Q

@require_POST
def search(request):
    wd = request.POST.get('wd').strip()
    if wd:
        con = Q()
        for word in wd.split(' '):
            con = con | Q(video_title__icontains = word)
        result = Video_info.objects.filter(con)
    else:
        result = Video_info.objects.none()
    context = {}
    context['result'] = result
    context['wd'] = wd
    return render(request , 'video/result.html' , context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{%static 'bootstrap-3.3.7/css/bootstrap.min.css'%}" rel="stylesheet">
    {% block head %}{% endblock %}
  </head>
  <body>
    {% include 'header.html' %}

    {%block content %}{% endblock %}
    <script src="{%static 'jquery-3.3.1.min.js'%}"></script>
    <script src="{%static 'bootstrap-3.3.7/js/bootstrap.min.js'%}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/base_index.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- 标题 -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">视频网</a>
    </div>
    <!-- 导航 -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'list_type' %}?video_type=电影">电影</a></li>
        <li><a href="{% url 'list_type' %}?video_type=电视剧">电视剧</a></li>
        <li><a href="{% url 'list_type' %}?video_type=教程">教程</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block index_body %}
{% endblock%}
{% endblock %}

templates/header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- 标题 -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">视频网</a>
    </div>
    <!-- 导航 -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'list_type' %}?video_type=电影">电影</a></li>
        <li><a href="{% url 'list_type' %}?video_type=电视剧">电视剧</a></li>
        <li><a href="{% url 'list_type' %}?video_type=教程">教程</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}主页{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for video in list_video%}
        <div class="col-xs-6 col-md-2">
            <div class="thumbnail">
                <a href="{% url 'list_video' %}?video_info_id={{video.id}}"><img src="{{video.video_img.url}}"></a>
                <div class="caption">
                    <h5>{{video.video_title}}</h5>
                </div>    
            </div>
        </div>
        {% endfor %}
</div>
</div>
{% endblock %}

templates/list_type.html
{% extends 'base.html' %}

{% block title %}分类列表{% endblock %}

{% block content %}
    <div class="container">
    <div class="row">
        {% for video in list_video%}
        <div class="col-xs-6 col-md-2">
            <div class="thumbnail">
                <a href="{% url 'list_video' %}?video_info_id={{video.id}}"><img src="{{video.video_img.url}}"></a>
                <div class="caption">
                    <h5>{{video.video_title}}</h5>
                </div>    
            </div>
        </div>
        {% endfor %}
</div>
</div>
{% endblock%}

templates/list_video.html
{% extends 'base.html' %}

{% block title %}播放列表{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
            <div class="media">
                <div class="media-left" style="width: 30%">
                        <img class="media-object" src="{{video.video_img.url}}" style="width:100%">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{video.video_title}}</h4>
                    <p><hr></p>
                    <p>{{video.video_detail}}</p>
                </div>
            </div>       
    </div>
    <div class="row" style="padding-top: 20px">
        {% for item in video.video_set.all%}
        <div class="col-xs-6 col-md-2" style="margin-bottom: 10px">
        <div class="btn-group" style="width: 100%">           
            <a class="btn btn-primary" href="{% url 'play_video' %}?video_id={{item.id}}" style="width: 100%">{{item.name}}</a>            
        </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/play_video.html
{% extends 'base.html' %}
{% load staticfiles%}

{% block title %}视频播放{% endblock %}

{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static 'video.js/video-js.min.css' %}">   
{% endblock%}

{% block content %}
    <video
        id="my-player"
        class="video-js"
        controls
        preload="auto"
        data-setup='{}'>
        <source src="{{video.video.url}}" type="video/mp4"></source>
    </video>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'video.js/video.min.js' %}"></script>
{% endblock %}

templates/video/base_video.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{%static 'bootstrap-3.3.7/css/bootstrap.min.css'%}" rel="stylesheet">
    {% block head %}{% endblock %}
  </head>
  <body>
    {% include 'video/header.html' %}

    {%block content %}{% endblock %}
    <script src="{%static 'jquery-3.3.1.min.js'%}"></script>
    <script src="{%static 'bootstrap-3.3.7/js/bootstrap.min.js'%}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/video/header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- 标题 -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">视频网</a>
    </div>
    <!-- 导航 -->
    <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'list_type' %}?video_type=电影">电影</a></li>
        <li><a href="{% url 'list_type' %}?video_type=电视剧">电视剧</a></li>
        <li><a href="{% url 'list_type' %}?video_type=教程">教程</a></li>
      </ul>
      <form class="navbar-form navbar-left" method="POST" action="{% url 'search' %}">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="wd">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
    </div>
  </div>
</nav>

templates/video/index.html
{% extends 'video/base_video.html' %}

{% block title %}主页{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for video in list_video%}
        <div class="col-xs-6 col-md-3">
            <div class="thumbnail">
                <a href="{% url 'list_video' %}?video_info_id={{video.id}}"><img src="{{video.video_img.url}}"></a>
                <div class="caption">
                    <h5>{{video.video_title}}</h5>
                </div>    
            </div>
        </div>
        {% endfor %}
</div>
</div>
{% endblock %}

templates/video/list_type.html
{% extends 'video/base_video.html' %}

{% block title %}分类列表{% endblock %}

{% block content %}
    <div class="container">
    <div class="row">
        {% for video in list_video%}
        <div class="col-xs-6 col-md-3">
            <div class="thumbnail">
                <a href="{% url 'list_video' %}?video_info_id={{video.id}}"><img src="{{video.video_img.url}}"></a>
                <div class="caption">
                    <h5>{{video.video_title}}</h5>
                </div>    
            </div>
        </div>
        {% endfor %}
</div>
</div>
{% endblock%}

templates/video/list_video.html
{% extends 'video/base_video.html' %}

{% block title %}播放列表{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-5">
            <img src="{{ video.video_img.url }}" width="100%">
        </div>
        <div class="col-xs-7">
            <h4>{{ video.video_title }}</h4>
            <hr>
            <p>
                {{ video.video_detail }}
            </p>
        </div>
    </div>
    <div class="row" style="padding-top: 20px">
        {% for item in video.video_set.all%}
        <div class="col-xs-6 col-md-2" style="margin-bottom: 10px">
        <div class="btn-group" style="width: 100%">           
            <a class="btn btn-primary" href="{% url 'play_video' %}?video_id={{item.id}}" style="width: 100%">{{item.name}}</a>            
        </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/video/play_video.html
{% extends 'video/base_video.html' %}
{% load staticfiles%}

{% block title %}视频播放{% endblock %}

{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static 'video.js/video-js.min.css' %}">
        <link rel="stylesheet" href="{% static 'video.js/play_video.css' %}">   
{% endblock%}

{% block content %}
<div class="container">
    <div class="row text-center">
        <h4>{{ video.name }}</h4>
    </div>
    <div class="row" id="play_row">
        <div  id="play_container">
            <video
            id="my-player"
            class="video-js vjs-fluid"
            controls
            preload="auto"
            data-setup="{}"
            >
                <source src="{{video.video.url}}" type="video/mp4"></source>
            </video>
        </div>
              
    </div>
</div>
    
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'video.js/video.min.js' %}"></script>
<script>
videojs('my-player', {
  playbackRates: [0.5, 1, 1.5, 2],
});
</script>
{% endblock %}

templates/video/result.html
{% extends 'video/base_video.html' %}

{% block title %}查询结果{% endblock %}

{% block content %}
<div class="container">
    <div>
        <h4>
            查询“{{ wd }}”，找到{{ result.count }}个结果
        </h4>
    </div>
    <hr>
    <div>
        {% if wd %}
            {% for video_info in result %}
            <p><a href="{% url 'list_video' %}?video_info_id={{ video_info.id }}">{{ video_info.video_title }}</a></p>
            {% empty %}
            <p>没有找到任何结果</p>
            {% endfor %}
        {% else %}
            <p>请输入查询内容</p>
        {% endif %}
    </div>  
</div>
{% endblock %}